ERROR: from log-with-same-root-name.log.log